name: Roytravel
title: Roytravel | A blog theme for Jekyll
description: For world society.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: roytravel97@gmail.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
